### ISSUE TITLE
new keyword is missing in Circle class

### ISSUE THREAD

**Issue by foreverdeepak** [ahome-it/ahome-gmaps#1]
Library fails to draw the circle due to "new" keyword is missing in `createPeer()` and `createPeer(JavaScriptObject options)` methods.

Correct method body must be as follows:

```
    private static native JavaScriptObject createPeer()/*-{
        return new $wnd.google.maps.Circle();
    }-*/;

    private static native JavaScriptObject createPeer(JavaScriptObject options)/*-{
        return new $wnd.google.maps.Circle(options);
    }-*/;
```

**Comment by eemi2010** [comment]
Thx for reporting. Just fixed it here: https://github.com/ahome-it/ahome-gmaps/commit/2357c79980c92e78893c64db998c37b84ba36499
